apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kybertune-llmops
  namespace: argocd
spec:
  destination:
    namespace: kybertune
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infrastructure
    repoURL: https://github.com/zubeyirtosun/kybertune
    targetRevision: HEAD
    directory:
      exclude: >-
        {serving-deployment.yaml,serving-endpoint-update.yaml,kind-gpu-config.yaml,training-job.yaml}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
