kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kybertune-cluster
nodes:
- role: control-plane
- role: worker
  extraMounts:
    - hostPath: /dev/nvidia0 # Kendi pathlerinize göre düzenleyin
      containerPath: /dev/nvidia0
    - hostPath: /dev/nvidiactl # Kendi pathlerinize göre düzenleyin
      containerPath: /dev/nvidiactl
    - hostPath: /dev/nvidia-uvm # Kendi pathlerinize göre düzenleyin
      containerPath: /dev/nvidia-uvm
    - hostPath: /dev/nvidia-uvm-tools # Kendi pathlerinize göre düzenleyin
      containerPath: /dev/nvidia-uvm-tools
