kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kybertune-cluster
nodes:
- role: control-plane
- role: worker
  extraMounts:
    - hostPath: /dev/nvidia0
      containerPath: /dev/nvidia0
    - hostPath: /dev/nvidiactl
      containerPath: /dev/nvidiactl
    - hostPath: /dev/nvidia-uvm
      containerPath: /dev/nvidia-uvm
    - hostPath: /dev/nvidia-uvm-tools
      containerPath: /dev/nvidia-uvm-tools
